In [1]:
import pandas as pd
# Read the dataset
df=pd.read_csv("D:/internship/customers-100.csv")
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [2]:
# Summary of a DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [3]:
# Identify duplicate rows in a DataFrame
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [4]:
# Get all unique (distinct) values from the "First Name" column.
df['First Name'].unique()

array(['Sheryl', 'Preston', 'Roy', 'Linda', 'Joanna', 'Aimee', 'Darren',
       'Brett', 'Michelle', 'Carl', 'Jenna', 'Tracey', 'Kristine',
       'Faith', 'Miranda', 'Caroline', 'Greg', 'Clifford', 'Maxwell',
       'Kiara', 'Colleen', 'Janet', 'Shane', 'Marcus', 'Dakota',
       'Frederick', 'Stefanie', 'Kent', 'Jack', 'Tom', 'Gabriel',
       'Kaitlyn', 'Tammie', 'Nicholas', 'Jordan', 'Bruce', 'Sherry',
       'Natalie', 'Bryan', 'Wayne', 'Luis', 'Rhonda', 'Joanne',
       'Geoffrey', 'Gloria', 'Brady', 'Latoya', 'Gerald', 'Samuel',
       'Patricia', 'Stacie', 'Robin', 'Ralph', 'Phyllis', 'Danny',
       'Kathy', 'Kelli', 'Lynn', 'Shelley', 'Eddie', 'Chloe', 'Eileen',
       'Fernando', 'Makayla', 'Virginia', 'Riley', 'Alexandria',
       'Richard', 'Candice', 'Anita', 'Regina', 'Debra', 'Brittany',
       'Cassidy', 'Laurie', 'Alejandro', 'Leslie', 'Kathleen', 'Hunter',
       'Chad', 'Corey', 'Emma', 'Duane', 'Alison', 'Vernon', 'Lori',
       'Nina', 'Collin', 'Darrell', 'Karl', 'Fred', 'Yvonne', 'Clarence'],
      dtype=object)

In [5]:
# Returns the number of unique (distinct) values in the "First Name" column.
df['First Name'].nunique()

93

In [6]:
# Returns the frequency of each unique value in the "First Name" column.
df['First Name'].value_counts()

First Name
Sheryl      2
Joanna      2
Faith       2
Shane       2
Tom         2
           ..
Darrell     1
Karl        1
Fred        1
Yvonne      1
Clarence    1
Name: count, Length: 93, dtype: int64

In [7]:
# Find values that appear more than once in the "First Name" column using pandas.
counts = df['First Name'].value_counts()
counts[counts > 1]

First Name
Sheryl    2
Joanna    2
Faith     2
Shane     2
Tom       2
Sherry    2
Lynn      2
Name: count, dtype: int64

In [8]:
# Get all unique (distinct) values from the "Last Name" column.
df['Last Name'].unique()

array(['Baxter', 'Lozano', 'Berry', 'Olsen', 'Bender', 'Downs', 'Peck',
       'Mullen', 'Meyers', 'Gallagher', 'Schroeder', 'Dodson', 'Mata',
       'Cox', 'Lutz', 'Beasley', 'Foley', 'Jacobson', 'Kirk', 'Frye',
       'Houston', 'Howard', 'Valenzuela', 'Wilcox', 'Moody', 'Poole',
       'Harper', 'Fitzpatrick', 'Bradshaw', 'Tate', 'Trujillo', 'Mejia',
       'Santana', 'Moon', 'Haley', 'Sosa', 'Gay', 'Esparza', 'Garza',
       'Gentry', 'Dunn', 'Simpson', 'Greer', 'Frost', 'Montes', 'Guzman',
       'Mccall', 'Cohen', 'Mccann', 'Hawkins', 'Crawford', 'Goodwin',
       'Richard', 'West', 'Haas', 'Maldonado', 'Parrish', 'Hill', 'Hardy',
       'Pham', 'Harris', 'Jimenez', 'Hutchinson', 'Lynch', 'Lambert',
       'Cannon', 'Alvarado', 'Dudley', 'Good', 'Buck', 'Roth', 'Keller',
       'Benson', 'Stein', 'Riddle', 'Zuniga', 'Mcmahon', 'Pennington',
       'Blair', 'Jennings', 'Mckay', 'Moreno', 'Davidson', 'Holt',
       'Cunningham', 'Woods', 'Vargas', 'Kane', 'Flowers', 'Chavez',
       'Ayers', 'Young', 'Douglas', 'Atkinson', 'Guerra', 'Farmer',
       'Haynes'], dtype=object)

In [9]:
# Returns the number of unique (distinct) values in the "Last Name" column.
df['Last Name'].nunique()

97

In [10]:
# Get all unique (distinct) values from the "Company" column.
df['Company'].unique()

array(['Rasmussen Group', 'Vega-Gentry', 'Murillo-Perry',
       'Dominguez, Mcmillan and Donovan', 'Martin, Lang and Andrade',
       'Steele Group', 'Lester, Woodard and Mitchell',
       'Sanford, Davenport and Giles', 'Browning-Simon', 'Beck-Hendrix',
       'Oconnell, Meza and Everett', 'Hoffman, Reed and Mcclain',
       'Graham-Francis', 'Carpenter-Cook', 'Carter-Hancock',
       'Singleton and Sons', 'Winters-Mendoza', 'Valentine LLC',
       'Simon LLC', 'Mays-Mccormick', 'Patterson Inc',
       'Manning, Hester and Arroyo', 'Greer and Sons', 'Watts-Donaldson',
       'Tucker LLC', 'Giles Ltd', 'Simmons Group',
       'Hinton, Chaney and Stokes', 'Santana-Duran', 'Sawyer PLC',
       'Acosta, Petersen and Morrow', 'Mcgee Group', 'Adkins-Salinas',
       'Herrera Group', 'Waters, Chase and Aguilar',
       'Palmer, Barnes and Houston', 'Jordan Ltd', 'Glover and Sons',
       'Huerta-Mclean', 'Anderson Ltd', 'Monroe PLC', 'Kaufman and Sons',
       'Perkins-Trevino', 'Cross PLC', 'Herrera, Shepherd and Underwood',
       'Price, Sexton and Mcdaniel', 'Short-Wiggins',
       'Brennan, Acosta and Ramos', 'Osborne-Erickson',
       'Hobbs, Garrett and Sanford', 'Phelps, Forbes and Koch',
       'May, Goodwin and Martin', 'Christian, Winters and Ellis',
       'Byrd Inc', 'Nixon, Blackwell and Sosa', 'Montes PLC', 'Costa PLC',
       'Novak LLC', 'Moore, Mccoy and Glass', 'Petty Ltd',
       'Brennan, Camacho and Tapia', 'Prince, Malone and Pugh',
       'Caldwell Group', 'Knight, Abbott and Hubbard', 'Church-Banks',
       'Henderson Inc', 'Donaldson-Dougherty', 'Warren Ltd', 'Wade PLC',
       'Keller-Coffey', 'Conway-Mcbride', 'Huynh and Sons', 'Parrish Ltd',
       'Guzman-Brown', 'Chang, Aguirre and Leblanc', 'Mason-Hester',
       'Mcguire, Huynh and Hopkins', 'Sanchez, Marsh and Hale',
       'Combs, Waller and Durham', 'Blankenship-Arias',
       'Coffey, Lamb and Johnson', 'Fitzpatrick-Lawrence',
       'Garcia-Jimenez', 'Mcdonald, Bird and Ramirez', 'Stephens Inc',
       'Montoya-Miller', 'Vaughn, Watts and Leach', 'Carter-Strickland',
       'Decker-Mcknight', 'Byrd-Campbell', 'Rocha-Hart', 'Lamb-Peterson',
       'Lee, Lucero and Johnson', 'Newton, Petersen and Mathis',
       'Carey LLC', 'Ware, Burns and Oneal', 'Schmitt-Jones',
       'Fitzgerald-Harrell', 'Le, Nash and Cross'], dtype=object)

In [11]:
# Returns the number of unique (distinct) values in the "Company" column.
df['Company'].nunique()

99

In [12]:
# Get all unique (distinct) values from the "Subscription Date" column.
df['Subscription Date'].unique()

array(['2020-08-24', '2021-04-23', '2020-03-25', '2020-06-02',
       '2021-04-17', '2020-02-25', '2021-08-24', '2021-04-12',
       '2020-01-13', '2021-11-08', '2021-10-20', '2020-11-29',
       '2021-12-02', '2021-02-08', '2022-01-26', '2022-04-12',
       '2021-03-10', '2022-03-26', '2020-09-24', '2021-09-24',
       '2022-01-12', '2020-09-15', '2020-08-19', '2020-09-08',
       '2021-04-06', '2022-05-24', '2022-02-20', '2022-05-26',
       '2020-07-30', '2020-04-26', '2021-09-15', '2022-01-13',
       '2021-04-24', '2021-09-21', '2021-11-03', '2022-01-04',
       '2021-08-10', '2021-02-24', '2021-10-22', '2021-11-01',
       '2020-10-10', '2021-09-08', '2020-12-13', '2022-05-15',
       '2021-12-06', '2020-07-01', '2020-04-23', '2022-03-11',
       '2022-03-10', '2021-03-19', '2021-03-27', '2021-03-08',
       '2020-10-15', '2020-05-25', '2021-01-25', '2021-03-17',
       '2020-11-15', '2020-12-20', '2020-08-21', '2020-12-10',
       '2022-03-24', '2021-01-02', '2020-01-20', '2020-08-18',
       '2021-01-31', '2020-02-03', '2021-02-20', '2020-02-23',
       '2020-08-22', '2020-02-09', '2022-01-15', '2020-07-11',
       '2021-07-24', '2020-10-21', '2020-06-08', '2020-09-19',
       '2021-11-13', '2021-09-12', '2020-12-28', '2021-11-15',
       '2020-02-18', '2022-05-13', '2020-07-21', '2020-11-10',
       '2021-04-15', '2021-01-09', '2020-03-26', '2021-07-06',
       '2021-06-29', '2021-04-04', '2022-02-17', '2022-01-30',
       '2021-07-10', '2021-09-18', '2021-08-11', '2020-03-11'],
      dtype=object)

In [13]:
# # Returns the number of unique (distinct) values in the "Subscription Date" column.
df['Subscription Date'].nunique()

96

In [14]:
# This line creates a new column "Full Name" by combining "First Name" and "Last Name" in a pandas DataFrame.
df['Full Name'] = df['First Name'] + ' ' + df['Last Name']

In [15]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Full Name
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,Sheryl Baxter
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,Preston Lozano
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,Roy Berry
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,Linda Olsen
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,Joanna Bender
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,Karl Greer
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,Lynn Atkinson
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,Fred Guerra
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,Yvonne Farmer
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,Clarence Haynes

In [16]:
# This line removes specific columns from your DataFrame in pandas.
df=df.drop(columns=['First Name','Last Name','Customer Id','Phone 2'])
df

,Index,Company,City,Country,Phone 1,Email,Subscription Date,Website,Full Name
0,1,Rasmussen Group,East Leonard,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,Sheryl Baxter
1,2,Vega-Gentry,East Jimmychester,Djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/,Preston Lozano
2,3,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,Roy Berry
3,4,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,Linda Olsen
4,5,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,Joanna Bender
...,...,...,...,...,...,...,...,...,...
95,96,Carey LLC,East Richard,Guyana,(188)169-1674x58692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,Karl Greer
96,97,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,Lynn Atkinson
97,98,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,swagner@kane.org,2021-09-18,https://www.ross.com/,Fred Guerra
98,99,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,Yvonne Farmer
99,100,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,Clarence Haynes

In [17]:
# Count missing values in each column of a DataFrame.
df.isna().sum()

Index                0
Company              0
City                 0
Country              0
Phone 1              0
Email                0
Subscription Date    0
Website              0
Full Name            0
dtype: int64

In [18]:
# This line converts a column into proper date/time format using pandas.
df['Subscription Date'] = pd.to_datetime(df['Subscription Date'])
df

,Index,Company,City,Country,Phone 1,Email,Subscription Date,Website,Full Name
0,1,Rasmussen Group,East Leonard,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,Sheryl Baxter
1,2,Vega-Gentry,East Jimmychester,Djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/,Preston Lozano
2,3,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,Roy Berry
3,4,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,Linda Olsen
4,5,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,Joanna Bender
...,...,...,...,...,...,...,...,...,...
95,96,Carey LLC,East Richard,Guyana,(188)169-1674x58692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,Karl Greer
96,97,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,Lynn Atkinson
97,98,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,swagner@kane.org,2021-09-18,https://www.ross.com/,Fred Guerra
98,99,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,Yvonne Farmer
99,100,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,Clarence Haynes

In [19]:
# This code is using pandas to convert multiple text columns to lowercase.
cols = ['Company', 'City', 'Country','Full Name']

df[cols] = df[cols].apply(lambda x: x.str.lower())
df

,Index,Company,City,Country,Phone 1,Email,Subscription Date,Website,Full Name
0,1,rasmussen group,east leonard,chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,sheryl baxter
1,2,vega-gentry,east jimmychester,djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/,preston lozano
2,3,murillo-perry,isabelborough,antigua and barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,roy berry
3,4,"dominguez, mcmillan and donovan",bensonview,dominican republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,linda olsen
4,5,"martin, lang and andrade",west priscilla,slovakia (slovak republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,joanna bender
...,...,...,...,...,...,...,...,...,...
95,96,carey llc,east richard,guyana,(188)169-1674x58692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,karl greer
96,97,"ware, burns and oneal",new bradview,sri lanka,+1-846-706-2218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,lynn atkinson
97,98,schmitt-jones,ortegaland,solomon islands,+1-753-067-8419x7170,swagner@kane.org,2021-09-18,https://www.ross.com/,fred guerra
98,99,fitzgerald-harrell,lake elijahview,aruba,(530)311-9786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,yvonne farmer
99,100,"le, nash and cross",judymouth,honduras,(753)813-6941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,clarence haynes

In [20]:
# This line cleans a phone number column using pandas by removing all non-digit characters.
df['Phone 1'] = df['Phone 1'].str.replace(r'\D', '', regex=True)
df

,Index,Company,City,Country,Phone 1,Email,Subscription Date,Website,Full Name
0,1,rasmussen group,east leonard,chile,2290775154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,sheryl baxter
1,2,vega-gentry,east jimmychester,djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/,preston lozano
2,3,murillo-perry,isabelborough,antigua and barbuda,15394020259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,roy berry
3,4,"dominguez, mcmillan and donovan",bensonview,dominican republic,001808617646712895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,linda olsen
4,5,"martin, lang and andrade",west priscilla,slovakia (slovak republic),001234203063576146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,joanna bender
...,...,...,...,...,...,...,...,...,...
95,96,carey llc,east richard,guyana,188169167458692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,karl greer
96,97,"ware, burns and oneal",new bradview,sri lanka,18467062218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,lynn atkinson
97,98,schmitt-jones,ortegaland,solomon islands,175306784197170,swagner@kane.org,2021-09-18,https://www.ross.com/,fred guerra
98,99,fitzgerald-harrell,lake elijahview,aruba,5303119786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,yvonne farmer
99,100,"le, nash and cross",judymouth,honduras,7538136941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,clarence haynes

In [21]:
# Count missing values in each column of a DataFrame.
df.isna().sum()

Index                0
Company              0
City                 0
Country              0
Phone 1              0
Email                0
Subscription Date    0
Website              0
Full Name            0
dtype: int64

In [22]:
# Count how many duplicate rows exist in a DataFrame.
df.duplicated().sum()

np.int64(0)